// File generated by Antigravity from google-services.json for cosmyra-edu
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_NEW_API_KEY',
    appId: '1:YOUR_NEW_PROJECT_NUMBER:android:placeholder',
    messagingSenderId: 'YOUR_NEW_PROJECT_NUMBER',
    projectId: 'YOUR_NEW_PROJECT_ID',
    storageBucket: 'YOUR_NEW_PROJECT.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_NEW_API_KEY',
    appId: '1:YOUR_NEW_PROJECT_NUMBER:ios:placeholder',
    messagingSenderId: 'YOUR_NEW_PROJECT_NUMBER',
    projectId: 'YOUR_NEW_PROJECT_ID',
    storageBucket: 'YOUR_NEW_PROJECT.appspot.com',
    iosBundleId: 'com.cosmyra.neetjee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_NEW_API_KEY',
    appId: '1:YOUR_NEW_PROJECT_NUMBER:ios:placeholder',
    messagingSenderId: 'YOUR_NEW_PROJECT_NUMBER',
    projectId: 'YOUR_NEW_PROJECT_ID',
    storageBucket: 'YOUR_NEW_PROJECT.appspot.com',
    iosBundleId: 'com.cosmyra.neetjee',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_NEW_API_KEY',
    appId: '1:YOUR_NEW_PROJECT_NUMBER:web:placeholder',
    messagingSenderId: 'YOUR_NEW_PROJECT_NUMBER',
    projectId: 'YOUR_NEW_PROJECT_ID',
    storageBucket: 'YOUR_NEW_PROJECT.appspot.com',
  );
}
