// File generated by Antigravity from google-services.json for cosmyra-edu
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1bSXD1ho4dLeamygyeTbLCO3FLxoxfs',
    appId: '1:672019832931:android:f306b7e0c88a9c9aaf9856',
    messagingSenderId: '672019832931',
    projectId: 'cosmyra-edu',
    storageBucket: 'cosmyra-edu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1bSXD1ho4dLeamygyeTbLCO3FLxoxfs',
    appId: '1:672019832931:ios:f306b7e0c88a9c9aaf9856',
    messagingSenderId: '672019832931',
    projectId: 'cosmyra-edu',
    storageBucket: 'cosmyra-edu.firebasestorage.app',
    iosBundleId: 'com.cosmyra.neetjee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1bSXD1ho4dLeamygyeTbLCO3FLxoxfs',
    appId: '1:672019832931:ios:f306b7e0c88a9c9aaf9856',
    messagingSenderId: '672019832931',
    projectId: 'cosmyra-edu',
    storageBucket: 'cosmyra-edu.firebasestorage.app',
    iosBundleId: 'com.cosmyra.neetjee',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP1bSXD1ho4dLeamygyeTbLCO3FLxoxfs',
    appId: '1:672019832931:web:f306b7e0c88a9c9aaf9856',
    messagingSenderId: '672019832931',
    projectId: 'cosmyra-edu',
    storageBucket: 'cosmyra-edu.firebasestorage.app',
  );
}
